{
  "openapi": "3.0.0",
  "paths": {
    "/": {
      "get": {
        "operationId": "AppController_getHello",
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        }
      }
    },
    "/google": {
      "post": {
        "operationId": "AuthController_googleAuth",
        "parameters": [],
        "responses": {
          "201": {
            "description": ""
          }
        },
        "tags": [
          "auth"
        ]
      }
    },
    "/google/redirect": {
      "get": {
        "operationId": "AuthController_googleAuthRedirect",
        "parameters": [],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "tags": [
          "auth"
        ]
      }
    }
  },
  "info": {
    "title": "Career Climb",
    "description": "The Career Climb API description",
    "version": "1.0",
    "contact": {}
  },
  "tags": [
    {
      "name": "CareerClimb",
      "description": ""
    }
  ],
  "servers": [],
  "components": {
    "schemas": {}
  }
}
